project_name: krew-plugin-demo
release:
  github:
    owner: ankithans
    name: krew-plugin-demo
builds:
  - id: krew-plugin-demo
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/ankithans/krew-plugin-demo/pkg/version.version=
archives:
  - id: krew-plugin-demo
    builds:
    - krew-plugin-demo
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
