apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: krew-plugin-demo
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/ankithans/krew-plugin-demo/releases/download/v0.1.0/krew-plugin-demo_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./krew-plugin-demo"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-demo"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/ankithans/krew-plugin-demo/releases/download/v0.1.0/krew-plugin-demo_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./krew-plugin-demo"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-demo"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/ankithans/krew-plugin-demo/releases/download/v0.1.0/krew-plugin-demo_windows_amd64.zip
    sha256: ""
    files:
    - from: "/krew-plugin-demo.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-demo.exe"
  shortDescription: A new plugin
  homepage: https://github.com/ankithans/krew-plugin-demo
  caveats: |
    Usage:
      $ kubectl krew-plugin-demo

    For additional options:
      $ kubectl krew-plugin-demo --help
      or https://github.com/ankithans/krew-plugin-demo/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
